export const LOAD_ARTICLES_REQUEST = 'LOAD_ARTICLES_REQUEST';
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const LOAD_ARTICLES_FAILURE = 'LOAD_ARTICLES_FAILURE';

export const INIT_SUBMIT_NEW_ARTICLE_REQUEST = 'INIT_SUBMIT_NEW_ARTICLE_REQUEST';
export const INIT_SUBMIT_NEW_ARTICLE_SUCCESS = 'INIT_SUBMIT_NEW_ARTICLE_SUCCESS';
export const INIT_SUBMIT_NEW_ARTICLE_FAILURE = 'INIT_SUBMIT_NEW_ARTICLE_FAILURE';

export const SUBMIT_ARTICLE_VERSION_REQUEST = 'SUBMIT_ARTICLE_VERSION_REQUEST';
export const SUBMIT_ARTICLE_VERSION_SUCCESS = 'SUBMIT_ARTICLE_VERSION_SUCCESS';
export const SUBMIT_ARTICLE_VERSION_FAILURE = 'SUBMIT_ARTICLE_VERSION_FAILURE';

export const SUBMIT_COMMENT_REQUEST = 'SUBMIT_COMMENT_REQUEST';
export const SUBMIT_COMMENT_SUCCESS = 'SUBMIT_COMMENT_SUCCESS';
export const SUBMIT_COMMENT_FAILURE = 'SUBMIT_COMMENT_FAILURE';

export const LOAD_CURRENT_ARTICLE_VERSIONS_REQUEST = 'LOAD_CURRENT_ARTICLE_VERSIONS_REQUEST';
export const LOAD_CURRENT_ARTICLE_VERSIONS_SUCCESS = 'LOAD_CURRENT_ARTICLE_VERSIONS_SUCCESS';
export const LOAD_CURRENT_ARTICLE_VERSIONS_FAILURE = 'LOAD_CURRENT_ARTICLE_VERSIONS_FAILURE';

export const PICKUP_ARTICLE_VERSION = 'PICKUP_ARTICLE_VERSION';

export const INIT_CREATION_ARTICLE_VERSION = 'INIT_CREATION_ARTICLE_VERSION';

export const INIT_CREATION_NEW_ARTICLE = 'INIT_CREATION_NEW_ARTICLE';


export const VOTE_UP_START = 'VOTE_UP_START';
export const VOTE_UP_SUCCESS = 'VOTE_UP_SUCCESS';
export const VOTE_UP_FAILURE = 'VOTE_UP_FAILURE';

export const VOTE_DOWN_START = 'VOTE_DOWN_START';
export const VOTE_DOWN_SUCCESS = 'VOTE_DOWN_SUCCESS';
export const VOTE_DOWN_FAILURE = 'VOTE_DOWN_FAILURE';
